#!/bin/sh

set -e

cd "$(dirname "$0")/.."


if ! python3 -c "import hass_nabucasa" 2>/dev/null; then
  if ! coreversion=$(curl -fsSL https://version.home-assistant.io/beta.json | jq -er '.homeassistant.default'); then
    echo "Failed to get the Home Assistant Core beta version from https://version.home-assistant.io/beta.json" >&2
    exit 1
  fi
  if ! corehassnabucasa=$(curl -fsSL "https://raw.githubusercontent.com/home-assistant/core/refs/tags/${coreversion}/homeassistant/components/cloud/manifest.json" | jq -er '.requirements[]' | grep -E '^hass-nabucasa'); then
    echo "Failed to find the hass-nabucasa requirement for Home Assistant Core ${coreversion}" >&2
    exit 1
  fi
  python3 -m pip install "${corehassnabucasa}"
fi
mkdir -p _data

python3 -c '
import json
from hass_nabucasa.voice_data import TTS_VOICES
print(json.dumps(TTS_VOICES, indent=2))
' > _data/ttsLanguages.json

python3 -c '
import json
from hass_nabucasa.voice import STT_LANGUAGES
print(json.dumps(STT_LANGUAGES, indent=2))
' > _data/sttLanguages.json
